# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: /
    schedule:
      interval: "monthly"
    versioning-strategy: increase-if-necessary
    commit-message:
      prefix: "build"
      prefix-development: "build"
    groups:
      "babel":
        patterns:
          - "@babel/*"
      "lodash":
        patterns:
          - "lodash*"
