name: Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Start docker containers
        run: docker-compose -f docker-compose.yml up -d
      - name: Install dependencies
        run: docker-compose run node yarn install --frozen-lockfile
      - name: Run tests
        run: docker-compose run node yarn test
